### ISSUE TITLE
Error in run dev

### ISSUE THREAD

**Issue by talmax1124** [chec/commercejs-nextjs-demo-store#192]
TypeError: Cannot read property 'tap' of undefined
    at /Users/carlitos/Joannie-Store/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js:100:61
    at SyncHook.eval [as call] (eval at create (/Users/carlitos/Joannie-Store/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/carlitos/Joannie-Store/node_modules/next/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/carlitos/Joannie-Store/node_modules/next/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/carlitos/Joannie-Store/node_modules/next/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/carlitos/Joannie-Store/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/carlitos/Joannie-Store/node_modules/next/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/carlitos/Joannie-Store/node_modules/next/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/carlitos/Joannie-Store/node_modules/next/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/carlitos/Joannie-Store/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

**Comment by talmax1124** [comment]
Already did what it said but no luck

**Comment by talmax1124** [comment]
Is there a solution?

**Comment by robbieaverill** [comment]
Hi @talmax1124, sorry for the late reply. Can you please explain what you've done in order to produce this issue, as well as the version of node you're using?

When I run `yarn dev` in this project on my machine I do not get this error. I'm using v12.20.0
