### ISSUE TITLE
Command failed with exit code 1: yarn deploy

### ISSUE THREAD

**Issue by lborruto** [chec/commercejs-nextjs-demo-store#88]
Hello! Building with Netlify, I got error when website is deployed : 

```
1:22:20 PM: ┌─────────────────────────────┐
1:22:20 PM: │        Netlify Build        │
1:22:20 PM: └─────────────────────────────┘
1:22:20 PM: ​
1:22:20 PM: ❯ Version
1:22:20 PM:   @netlify/build 3.1.10
1:22:20 PM: ​
1:22:20 PM: ❯ Flags
1:22:20 PM:   deployId: 5f2d3943799009008fb82918
1:22:20 PM:   mode: buildbot
1:22:20 PM:   timersFile: /tmp/substage_times.txt
1:22:20 PM: ​
1:22:20 PM: ❯ Current directory
1:22:20 PM:   /opt/build/repo
1:22:20 PM: ​
1:22:20 PM: ❯ Config file
1:22:20 PM:   /opt/build/repo/netlify.toml
1:22:20 PM: ​
1:22:20 PM: ❯ Context
1:22:20 PM:   production
1:22:20 PM: ​
1:22:20 PM: ❯ Loading plugins
1:22:20 PM:    - netlify-plugin-onboarding@1.0.0 from netlify.toml and package.json
1:22:20 PM: ​
1:22:20 PM: ┌──────────────────────────────────────────────────────┐
1:22:20 PM: │ 1. onPreBuild command from netlify-plugin-onboarding │
1:22:20 PM: └──────────────────────────────────────────────────────┘
1:22:20 PM: ​
1:22:20 PM: ​
1:22:20 PM: (netlify-plugin-onboarding onPreBuild completed in 5ms)
1:22:20 PM: ​
1:22:20 PM: ┌────────────────────────────────────┐
1:22:20 PM: │ 2. build.command from netlify.toml │
1:22:20 PM: └────────────────────────────────────┘
1:22:20 PM: ​
1:22:20 PM: $ yarn deploy
1:22:21 PM: yarn run v1.22.4
1:22:21 PM: $ next build && next export
1:22:21 PM: Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
1:22:21 PM: Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
1:22:21 PM: Creating an optimized production build...
1:22:22 PM: Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
1:22:22 PM: See here for more info: https://err.sh/next.js/built-in-css-disabled
1:22:48 PM: Compiled successfully.
1:22:48 PM: 
1:22:48 PM: Automatically optimizing pages...
1:22:48 PM: Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`.
1:22:48 PM: Read more: https://err.sh/next.js/opt-out-auto-static-optimization
1:22:50 PM: > Build error occurred
1:22:50 PM: TypeError: Cannot read property 'map' of undefined
1:22:50 PM:     at getStaticPaths (/opt/build/repo/.next/server/static/HEPUvl8hVstwABV3n7nTb/pages/product/[permalink].js:2546:26)
1:22:50 PM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
1:22:50 PM:     at async buildStaticPaths (/opt/build/repo/node_modules/next/dist/build/utils.js:18:80)
1:22:50 PM:     at async Object.isPageStatic (/opt/build/repo/node_modules/next/dist/build/utils.js:25:542) {
1:22:50 PM:   type: 'TypeError'
1:22:50 PM: }
1:22:50 PM: error Command failed with exit code 1.
1:22:50 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1:22:50 PM: ​
1:22:50 PM: ┌─────────────────────────────┐
1:22:50 PM: │   "build.command" failed    │
1:22:50 PM: └─────────────────────────────┘
1:22:50 PM: ​
1:22:50 PM:   Error message
1:22:50 PM:   Command failed with exit code 1: yarn deploy
1:22:50 PM: ​
1:22:50 PM:   Error location
1:22:50 PM:   In build.command from netlify.toml:
1:22:50 PM:   yarn deploy
1:22:50 PM: ​
1:22:50 PM:   Resolved config
1:22:50 PM:   build:
1:22:50 PM:     command: yarn deploy
1:22:50 PM:     commandOrigin: config
1:22:50 PM:     environment:
1:22:50 PM:       - CHEC_PUBLIC_KEY
1:22:50 PM:     publish: /opt/build/repo/out
1:22:50 PM:   plugins:
1:22:50 PM:     - inputs: {}
1:22:50 PM:       origin: config
1:22:50 PM:       package: netlify-plugin-onboarding
1:22:50 PM: Caching artifacts
1:22:50 PM: Started saving node modules
1:22:50 PM: Finished saving node modules
1:22:50 PM: Started saving build plugins
1:22:50 PM: Finished saving build plugins
1:22:50 PM: Started saving yarn cache
1:22:50 PM: Finished saving yarn cache
1:22:50 PM: Started saving pip cache
1:22:50 PM: Finished saving pip cache
1:22:50 PM: Started saving emacs cask dependencies
1:22:50 PM: Finished saving emacs cask dependencies
1:22:50 PM: Started saving maven dependencies
1:22:50 PM: Finished saving maven dependencies
1:22:50 PM: Started saving boot dependencies
1:22:50 PM: Finished saving boot dependencies
1:22:50 PM: Started saving go dependencies
1:22:50 PM: Finished saving go dependencies
1:22:52 PM: Error running command: Build script returned non-zero exit code: 1
1:22:52 PM: Failing build: Failed to build site
1:22:53 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
1:22:53 PM: Finished processing build request in 1m11.744157387s

```

My key is in the right place : 

![Screenshot_4](https://user-images.githubusercontent.com/33548688/89641388-da35ee80-d8b1-11ea-85ba-1a981ec5ee35.png)

**Comment by lborruto** [comment]
Still same error, am I doing something wrong?

**Comment by jaepass** [comment]
Hii are you a part of our community here http://slack.commercejs.com/? We can work out the error in real-time there.
I also just added this note https://github.com/chec/commercejs-nextjs-demo-store#one-click-deploy-with-netlify-recommended to explain both deploy processes

**Comment by jaepass** [comment]
> Still same error, am I doing something wrong? @robbieaverill @jaepass

Hii are you a part of our community here http://slack.commercejs.com/? We can work out the error in real-time there.
I also just added this note https://github.com/chec/commercejs-nextjs-demo-store#one-click-deploy-with-netlify-recommended to explain both deploy processes

**Comment by slavakurilyak** [comment]
I'm getting the same issue when deploying to Netlify for the first time

**Comment by jaepass** [comment]
Hi there, are you getting the same build error? A fix was recently pushed up to handle these errors https://github.com/chec/commercejs-nextjs-demo-store/pull/97. Are you deploying manually after making changes locally or using the one-click deploy feature? If you're using the one-click deploy for a quick preview, be sure to use the public key provided in the docs https://github.com/chec/commercejs-nextjs-demo-store#one-click-deploy-with-netlify-recommended. Please join our slack community if you have more questions! http://slack.commercejs.com/
